### ISSUE TITLE
生成的trainval_36.h5 中没有”cls_score“， 无法运行python tools/preprocess-hint.py --exp qa

### ISSUE THREAD

**Issue by alice-cool** [BierOne/VQA-AttReg#1]
Dear scholar,
    Where to download the (counterfactual ) data? I want to reproduce the result. Help for your reply.

**Comment by BierOne** [comment]
This work constructs the counterfactual data based on the QA pairs and the detected image attributes. If you need the image attributes, you can download them from [SelfCritical](https://github.com/jialinwu17/self_critical_vqa).

**Comment by alice-cool** [comment]
typer 报错可以参考这个
https://github.com/tiangolo/typer/pull/375

**Comment by alice-cool** [comment]
/home/bydd/VQA-AttReg/data/cpv2/glove6b_init_objects_300d.npy
https://github.com/jialinwu17/self_critical_vqa/tree/master/data 下有该名称，直接拷贝过来?

**Comment by alice-cool** [comment]
缺少文件：'/home/bydd/VQA-AttReg/data/cpv2/glove6b_init_objects_300d.npy'

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/189509041-891263cc-503f-4fc3-99dd-66d1118aa3fc.png)

在复现过程中，trainval_36.h5 的源文件是从tsv 中生成的。tsv 文件是从  hengyu_hu 的github download 链接下载的，但是用您的代码  preprocess_image_rcnn.py 无法生成 trainval_36.h5中想要的列表项，也就是无法训练整个模型例如列表项”cls_score“?

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/189509119-35ec4948-9732-4f64-817f-40fa77be73a5.png)

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/189509214-813a9897-2202-41ef-badd-360227953153.png)

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/189509366-be1a5e9b-1909-4f02-b02c-e02697363a31.png)

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/189509483-f0218235-9ced-4bf2-aa41-00906676e22d.png)

**Comment by BierOne** [comment]
Hi, 

1. h5中的cls_score是参照 selfcritic 所提供的image features的，建议去download [selfcritic](https://github.com/BierOne/VQA-AttReg/issues/1#issuecomment-1208858079)所提供的features
2. KeyError "question_type" 可以参考[compute_softscore.py(Line 214)](https://github.com/BierOne/VQA-AttReg/blob/master/tools/compute_softscore.py#L214)

**Comment by alice-cool** [comment]
能否提供一个baidu 下载features 链接，现在 self critical github 官网提供的是一个空链接，根本下载不了特征

**Comment by alice-cool** [comment]
还是希望您如果有图片特征，能否分享一下，我准备跟您的方法进行对比实验



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月12日(星期一) 中午1:12
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [BierOne/VQA-AttReg] 生成的trainval_36.h5 中没有”cls_score“， 无法运行python tools/preprocess-hint.py --exp qa (Issue #1)




 
Closed #1 as completed.

**Comment by alice-cool** [comment]
python tools/preprocess-hint.py --exp qa

出现：
attr 为“-” 会导致 attr 转换成空格，最终导致没有数据所有[0]索引越界（目前直接将‘-’这样子的attr 直接赋值成“none”，我认为都没啥语义应该没事吧）共有4212个“-”，相对于总数658111 比较少
![image](https://user-images.githubusercontent.com/16870890/191515686-a842b315-7c8e-42c4-a304-9bc14848c4fd.png)

![1663636654245](https://user-images.githubusercontent.com/16870890/191146425-4f6f58c8-6b34-423e-af1c-1dfdea3725f3.jpg)
![1663636792435](https://user-images.githubusercontent.com/16870890/191146704-b3706ef5-8678-4ff5-9a1c-555a73ff7efa.jpg)

**Comment by BierOne** [comment]
Hello, 抱歉，在我的服务器上测试，并没有出现这个情况。建议 你可以先统计一下这种情况的出现次数，如果次数比较少，可以尝试跳过试试。顺带一提，这份preprocess_hint.py的源码是提供自Selfcritic。

**Comment by alice-cool** [comment]
好的非常感谢解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月21日(星期三) 上午10:55
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [BierOne/VQA-AttReg] 生成的trainval_36.h5 中没有”cls_score“， 无法运行python tools/preprocess-hint.py --exp qa (Issue #1)




 
Hello, 抱歉，在我的服务器上测试，并没有出现这个情况。建议 你可以先统计一下这种情况的出现次数，如果次数比较少，可以尝试跳过试试。顺带一提，这份preprocess_hint.py的源码是提供自Selfcritic。
